# Generated by Django 6.0.1 on 2026-05-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_vendor_options_vendor_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_type',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PREMIUM', 'Premium')], default='PREMIUM', max_length=20),
        ),
    ]
