# Generated by Django 5.1 on 2026-05-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan_type',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('STARTER', 'Starter'), ('BUSINESS', 'Business'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('STARTER', 'Starter'), ('BUSINESS', 'Business')], max_length=100)),
                ('order_id', models.CharField(max_length=200, unique=True)),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('razorpay_signature', models.TextField()),
                ('payment_status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.company')),
            ],
        ),
    ]
