# Generated by Django 6.0.1 on 2026-05-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_is_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
