# Generated by Django 6.0.1 on 2026-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_phone'),
        ('inventory', '0032_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('company', 'order_number')},
        ),
    ]
