# Generated by Django 5.2.6 on 2026-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_phone'),
        ('inventory', '0033_alter_purchaseorder_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('company', 'gst_number')},
        ),
    ]
